node('docker') {
    def tag = 'latest'
    stage('Checkout') {
        git branch: "${env.branch}", credentialsId: 'git.matador', url: "${env.gitUrl}"

        def tempTag = sh script: 'git tag --points-at HEAD | tail -1', returnStdout: true

        if(tempTag != '') {
            tag = tempTag.trim()
        }

    }
    stage('Build & push to registry') {
        withDockerRegistry(credentialsId: 'pqm-registry.azure', url: 'https://vpcpqmregistry.azurecr.io') {
            def buildEnv = 'prod'
            sh "Docker/build.sh $tag ${buildEnv}"
        }

    }
   stage('Deploy') {
        def destDir = '/app/matadorsuite-web'
        def destHost = 'pqmadmin@10.5.1.11'
        sh "ssh ${destHost} docker-compose -f ${destDir}/docker-compose.yml pull matadorsuite-web"
        sh "ssh ${destHost} docker-compose -f ${destDir}/docker-compose.yml up -d --force-recreate matadorsuite-web"
    }
}
